### ISSUE TITLE
You use global vars 

### ISSUE THREAD

**Issue by SynthWeaver** [nlvo/web-app-from-scratch-1920#15]
https://github.com/nlvo/web-app-from-scratch-1920/blob/fee2a9910cb4d1b1c4ccd12635cbad171a8df311/docs/js/app.js#L1-L8

maybe read this ;)
http://wiki.c2.com/?GlobalVariablesAreBad

**Comment by nlvo** [comment]
Thanks, it was a temporary fix 😅. But it's fixed now.
