### ISSUE TITLE
Use a promise

### ISSUE THREAD

**Issue by SynthWeaver** [nlvo/web-app-from-scratch-1920#17]
You do not use a promise here, dont ask me how XD

https://github.com/nlvo/web-app-from-scratch-1920/blob/fee2a9910cb4d1b1c4ccd12635cbad171a8df311/docs/js/app.js#L10-L18

**Comment by nlvo** [comment]
A fetch is a promise right? Correct me if I'm wrong 😅.

**Comment by SynthWeaver** [comment]
I think so? Maybe ask a teacher to be sure?
